# Server configuration
server.port=${PORT:8080}

# Application Info
spring.application.name=bfhl-api

# Logging
logging.level.com.bajaj.bfhl=INFO
logging.level.org.springframework.web=WARN
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n

# Jackson - serialize only non-null fields globally
spring.jackson.default-property-inclusion=non_null
spring.jackson.serialization.write-dates-as-timestamps=false
